#!/bin/bash
#SBATCH --ntasks=180
#SBATCH --time=0-23:00:00
#SBATCH --account=ssc
#SBATCH --mail-user=paul.fleming@nrel.gov
#SBATCH --mail-type=ALL

module purge
module use /nopt/nrel/apps/modules/default/modulefiles
module load helics/helics-3.1.0_openmpi
module load netcdf-c/4.7.3/gcc-mpi

echo "Starting AMR-Wind job at: " $(date)

mpirun -n 180 /projects/ssc/amr-wind/amr-wind/build/amr_wind precursor_001.inp

echo "Finished AMR-Wind job at: " $(date)