#!/bin/bash
#SBATCH --ntasks=504
#SBATCH --time=10:00:00
#SBATCH --account=hfm

module purge
module use /nopt/nrel/apps/modules/default/modulefiles
module load helics/helics-3.1.0_openmpi
module load netcdf-c/4.7.3/gcc-mpi

echo "Starting AMR-Wind job at: " $(date)

mpirun -n 486 /lustre/eaglefs/scratch/mbrazell/moa_python/amr-wind/build/amr_wind precursor_003.inp > log

echo "Finished AMR-Wind job at: " $(date)
